# docker stack deploy -c stack.yml dns3l
# or: docker-compose -f stack.yml up [--build]

services:
  db:
    image: mariadb
    container_name: dns3l-mariadb
    restart: unless-stopped
    # environment:
    #   MARIADB_ROOT_PASSWORD: secret
    env_file:
      .env/db
    volumes:
      - dns3l-db:/var/lib/mysql
    networks:
      - dns3l
    dns_search: .
    healthcheck:
      disable: false
      test: [ "CMD-SHELL", "mariadb-admin ping -h localhost -u root -p$${MARIADB_ROOT_PASSWORD} || exit 1" ]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s

  ingress:
    image: ghcr.io/dns3l/ingress
    container_name: dns3l-ingress
    restart: unless-stopped
    build:
      context: ../ingress
      args:
        HTTP_PROXY: ${HTTP_PROXY}
        HTTPS_PROXY: ${HTTPS_PROXY}
        NO_PROXY: ${NO_PROXY}
    # volumes:
    #   - .env/nginx.conf:/etc/nginx.conf:ro
    env_file:
      .env/ingress
    networks:
      - dns3l
    dns_search: .
    ports:
      - 443:443
    depends_on:
      web:
        condition: service_healthy
      dns3ld:
        condition: service_healthy

  web:
    image: ghcr.io/dns3l/web
    container_name: dns3l-web
    restart: unless-stopped
    build:
      context: ../web
      args:
        HTTP_PROXY: ${HTTP_PROXY}
        HTTPS_PROXY: ${HTTPS_PROXY}
        NO_PROXY: ${NO_PROXY}
    # volumes:
    #   - .env/nuxt.config.js:/etc/nuxt.config.js:ro
    env_file:
      .env/web
    networks:
      - dns3l
    dns_search: .
    healthcheck:
      disable: false
      test: [ "CMD-SHELL", "curl -fsk -o /dev/null http://localhost:3000 || exit 1" ]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 15s

  # stack external auth1..n
  auth1:
    image: ghcr.io/dns3l/auth
    container_name: dns3l-auth1
    restart: unless-stopped
    build:
      context: ../auth
      args:
        HTTP_PROXY: ${HTTP_PROXY}
        HTTPS_PROXY: ${HTTPS_PROXY}
        NO_PROXY: ${NO_PROXY}
    # volumes:
    #   - .env/dex1.conf:/etc/dex.conf.yml:ro
    env_file:
      .env/auth1
    networks:
      - dns3l
    dns_search: .
    healthcheck:
      disable: false
      test: [ "CMD-SHELL", "curl -fsk -o /dev/null https://localhost:5554/auth/.well-known/openid-configuration || exit 1" ]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 15s

  dns3ld:
    image: ghcr.io/dns3l/dns3ld
    container_name: dns3l-dns3ld
    restart: unless-stopped
    build:
      context: ../dns3ld
      dockerfile: docker/Dockerfile-dns3ld
      args:
        HTTP_PROXY: ${HTTP_PROXY}
        HTTPS_PROXY: ${HTTPS_PROXY}
        NO_PROXY: ${NO_PROXY}
    volumes:
      - .env/dns3ld.conf:/etc/dns3ld.conf.yml:ro
    env_file:
      .env/dns3ld
    networks:
      - dns3l
    dns_search: .
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      disable: false
      test: [ "CMD-SHELL", "curl -fs -o /dev/null http://localhost:8880/api/info || exit 1" ]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  dns3l-db:

networks:
  dns3l:
    external: false
